# Site settings
title: Jurnal Lubna
description: Sepenggal narasi tentang hidup.
keywords: Modern, Blogging, Fun
author: Lubna
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
plugins: [jekyll-paginate] 
paginate: 6
paginate_path: "/page:num/"
